"use client";
import { useEffect, useState } from "react";
import { Anchor, ArrowDown, ArrowRight, Check, ExternalLink, Focus, Info, Layers3, LoaderCircle, Minus, Pause, Play, Plus, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import ImageComparison, {Panel} from "./image-comparison";
import ResultCharts from "./result-charts";
import {ko, modelName, pct} from "@/lib/display";
import Ocean from "./ocean";
import { validateEvidence, type Evidence, type Sample } from "@/lib/evidence";
export default function Home(){
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(""),[attempt,setAttempt]=useState(0);
 const [sampleId,setSampleId]=useState(""),[playing,setPlaying]=useState(false),[cameraCommand,setCameraCommand]=useState<{id:number;kind:"reset"|"in"|"out"}>({id:0,kind:"reset"}),[modelZoom,setModelZoom]=useState(1);
 const [resultModel,setResultModel]=useState("cnn"),[epsilon,setEpsilon]=useState(0.03),[className,setClassName]=useState("all");
 useEffect(()=>{let active=true;setError("");fetch("/evidence/data.json").then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{validateEvidence(d);if(active){setData(d);setSampleId(d.samples[0].id);}}).catch(()=>{if(active)setError("연구 기록을 확인하지 못했습니다. 확인되지 않은 수치는 표시하지 않습니다.");});return()=>{active=false};},[attempt]);
 const sample=data?.samples.find(s=>s.id===sampleId),summary=data?.results.find(r=>r.model===resultModel&&r.epsilon===epsilon);
 const result=className==="all"?summary:summary?.classes.find(c=>c.name===className);
 const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});
 const choose=(s:Sample)=>setSampleId(s.id);
 const cameraAction=(kind:"reset"|"in"|"out")=>{setPlaying(false);setCameraCommand(c=>({id:c.id+1,kind}));};
 return <main><header className="topbar"><a href="#" className="brand"><Anchor size={25}/><span>MARIS <small>해양 AI 실험실</small></span></a><nav><a href="#experiment">이미지 실험</a><a href="#results">전체 결과</a></nav><span className="replay-badge"><span/>기록된 결과 재생</span></header>
 <section className="scene-section" aria-label="설명용 3D 해상 장면">
  <div className="scene-intro"><span className="eyebrow">MARITIME ADVERSARIAL AI</span><p className="scene-kicker">선박을 관찰하고, 실제 실험으로 확인하세요.</p><h1>같은 선박,<br/>왜 AI의 판단은<br/>달라질까?</h1><p>선박 모형을 움직여 공간을 둘러본 뒤,<br/>실제 이미지에서 AI의 판단 변화를 확인하세요.</p><Button className="primary-action" onClick={()=>go("experiment")}>실제 이미지 비교하기 <ArrowDown size={17}/></Button><span className="scene-replay">저장된 실험 기록 재생 · 실시간 추론 아님</span></div>
  <div className="scene-workspace"><div className="scene-stage"><Ocean playing={playing} command={cameraCommand} onInteract={()=>setPlaying(false)} onZoom={setModelZoom}/><span className="scene-label">ILLUSTRATIVE MODEL / 설명용 모형</span><span className="orbit-hint">드래그로 회전 · 휠 / 두 손가락으로 확대</span></div><div className="orbit-controls"><div><Button variant="outline" aria-label="선박 축소" size="icon" onClick={()=>cameraAction("out")}><Minus/></Button><output aria-label="선박 확대 배율">{modelZoom.toFixed(1)}×</output><Button variant="outline" aria-label="선박 확대" size="icon" onClick={()=>cameraAction("in")}><Plus/></Button></div><Button variant="outline" onClick={()=>cameraAction("reset")}><RotateCcw size={15}/>시점 초기화</Button><Button variant="outline" aria-pressed={playing} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={15}/>:<Play size={15}/>}자동 회전 {playing?"끄기":"켜기"}</Button></div><p className="model-boundary">설명용 선박이며 실제 실험 이미지의 선박을 재현하지 않습니다. 항해 제어 실험이 아닙니다.</p></div>
 </section>
 <div className="experiment-body"><div className="flow-strip"><span className="active"><b>01</b> 이미지 선택</span><ArrowRight/><span><b>02</b> 판단 변화</span><ArrowRight/><a href="#results"><b>03</b> 전체 결과</a><span className="provisional">예비 연구 결과 · PROVISIONAL</span></div>
 {error?<div role="alert" className="load-state"><Info/><h2>결과 연결을 확인해주세요</h2><p>{error}</p><Button onClick={()=>setAttempt(attempt+1)}>다시 불러오기</Button></div>:!data||!sample?<div className="load-state" role="status"><LoaderCircle className="spin"/>확인된 실험 기록을 불러오는 중입니다.</div>:<>
 <section id="experiment" className="lab-section"><div className="section-heading"><div><span className="eyebrow">01 / IMAGE EXPERIMENT</span><h2>작은 변화가 만든 판단의 차이.</h2></div><p>저장된 비교 그림 {data.samples.length}개 · FGSM ε = {sample.epsilon}<br/><span>FGSM: 한 번의 픽셀 교란으로 오분류를 유도하는 방법</span></p></div>
 <div className="experiment-grid"><aside className="sample-picker"><div className="picker-title"><Layers3 size={17}/><h3>실험 이미지 선택</h3><span>{data.samples.length}</span></div><p>모델과 성공·실패를 함께 살펴보세요. 모든 사례의 강도는 ε = 0.03입니다.</p><div className="sample-list">{data.samples.map((s,i)=><button key={s.id} onClick={()=>choose(s)} className={`sample-card ${sample.id===s.id?"selected":""}`} aria-pressed={sample.id===s.id}><Panel sample={s} part={0} compact/><div><small>CASE {String(i+1).padStart(2,"0")} · {modelName(s.model)}</small><strong>{ko(s.truth)}</strong><span>{s.success?"공격 성공 · 오답 전환":"공격 실패 · 정답 유지"}</span></div>{sample.id===s.id&&<Check size={15}/>}</button>)}</div><div className="dataset-note"><Info size={16}/><p>현재 공개된 비교 PNG는 항공모함 {data.samples.length}개뿐입니다. 전체 {data.total}장이나 다른 선종의 대표 사례로 일반화할 수 없습니다.</p></div></aside>
 <ImageComparison key={sample.id} sample={sample}/></div>
 <div className="meaning-note"><Focus size={22}/><p><strong>이 실험이 보여주는 것</strong>입력 픽셀의 변화가 선박 분류에 미치는 영향입니다. 충돌·항로 이탈·센서 공격 또는 방어 효과를 측정한 결과는 아닙니다.</p><a href="#results">전체 기록 살펴보기 <ArrowDown size={16}/></a></div></section>
 <section id="results" className="results-section"><div className="section-heading"><div><span className="eyebrow">02 / EXPERIMENT EVIDENCE</span><h2>한 장을 넘어, 전체 실험으로.</h2></div><p>{data.total}장의 동일 테스트셋으로 비교한 기록<br/><span>실시간 추론 없이 저장된 수치를 재생합니다.</span></p></div><div className="selection-context"><div><b>전체 통계 선택</b><span>{modelName(resultModel)} · ε {epsilon} · {className==="all"?"전체 선박":ko(className)}</span></div><div><b>위 이미지 사례</b><span>{modelName(sample.model)} · ε {sample.epsilon} · {ko(sample.truth)}</span></div><Button variant="outline" onClick={()=>{setResultModel(sample.model);setEpsilon(sample.epsilon);setClassName(sample.truth);}}>통계를 사례 조건에 맞추기</Button><p>통계 선택은 위 이미지 사례를 바꾸지 않습니다. 서로 다른 조건을 살펴볼 수 있습니다.</p></div><div className="result-controls"><div><label htmlFor="result-model">모델</label><select id="result-model" value={resultModel} onChange={e=>setResultModel(e.target.value)}>{data.models.map(m=><option key={m} value={m}>{modelName(m)}</option>)}</select></div><div><label htmlFor="result-class">선박 클래스</label><select id="result-class" value={className} onChange={e=>setClassName(e.target.value)}><option value="all">전체 선박</option>{data.classNames.map(c=><option key={c} value={c}>{ko(c)}</option>)}</select></div><fieldset><legend>공격 강도 ε <span>픽셀 변화의 허용 크기</span></legend><div className="epsilon-options">{data.epsilons.map(e=><Button key={e} variant="outline" aria-pressed={epsilon===e} className={epsilon===e?"selected":""} onClick={()=>setEpsilon(e)}>{e===0?"0 · 대조군":e}</Button>)}</div></fieldset></div>
 {result&&<><div className="metric-grid"><div className="metric"><span>정상 정확도</span><strong>{pct(result.cleanCorrect/result.n)}</strong><small>전체 {result.n}장 중 {result.cleanCorrect}장 정답</small></div><div className="metric"><span>공격 후 정확도</span><strong>{pct(result.robustCorrect/result.n)}</strong><small>전체 {result.n}장 중 {result.robustCorrect}장 정답</small></div><div className="metric accent"><span>공격 성공률 <i>ASR</i></span><strong>{pct(result.asr)}</strong><small>정상 정답 {result.cleanCorrect}장 중 {result.successes}장 오답 전환</small></div></div><div className="chart-panel"><h3>공격 전부터 틀린 이미지와 구분합니다.</h3><p>ASR 분모에는 정상 입력에서 맞힌 이미지만 포함됩니다.</p><div className="composition" aria-label={`기존 오답 ${result.n-result.cleanCorrect}장, 공격으로 오답 ${result.successes}장, 정답 유지 ${result.cleanCorrect-result.successes}장`}><span className="preexisting" style={{width:`${(result.n-result.cleanCorrect)/result.n*100}%`}}/><span className="flipped" style={{width:`${result.successes/result.n*100}%`}}/><span className="retained" style={{width:`${(result.cleanCorrect-result.successes)/result.n*100}%`}}/></div><div className="chart-legend"><span><i className="preexisting"/>기존 오답 <b>{result.n-result.cleanCorrect}</b></span><span><i className="flipped"/>공격으로 오답 전환 <b>{result.successes}</b></span><span><i className="retained"/>정답 유지 <b>{result.cleanCorrect-result.successes}</b></span></div><small>기존 오답이 공격 후 정답으로 바뀌는 경우는 공격 후 정확도에는 포함되지만 ASR에는 포함되지 않습니다.</small></div></>}
 <ResultCharts data={data} className={className}/>
 <details className="record-table"><summary>전체 선박 · 두 모델 · 모든 강도 원수치 보기</summary><div className="table-scroll"><table><thead><tr><th>모델</th><th>ε</th><th>정상 정확도</th><th>공격 후 정확도</th><th>ASR</th><th>성공 / 분모</th></tr></thead><tbody>{data.results.map(r=><tr key={`${r.model}-${r.epsilon}`}><th>{modelName(r.model)}</th><td>{r.epsilon}</td><td>{pct(r.cleanCorrect/r.n)}</td><td>{pct(r.robustCorrect/r.n)}</td><td>{pct(r.asr)}</td><td>{r.successes} / {r.cleanCorrect}</td></tr>)}</tbody></table></div></details><div className="boundaries"><Info size={19}/><p>ε는 기록된 값만 선택할 수 있으며 보간하지 않습니다. 입력 해상도는 CNN 128×128, MobileNetV2 224×224로 다릅니다. MobileNetV2 학습 당시 전처리는 직접 확인되지 않았습니다. 결과는 예비 상태입니다.</p></div></section>
 <section className="missing-evidence" aria-label="연구 범위와 데이터 상세"><Accordion type="single" collapsible><AccordionItem value="research-data"><AccordionTrigger>연구 범위·데이터 안내</AccordionTrigger><AccordionContent><h4>다른 선종의 비교는 언제 추가되나요?</h4><p>검증된 실제 비교 자료가 확보되면 추가합니다. 현재 항공모함 사례만으로 다른 선종이나 전체 실험을 대표한다고 볼 수 없습니다.</p><h4>더 정밀한 차이 분석에 필요한 자료</h4><p>같은 표본의 정상·공격 입력 배열(NPY/NPZ), 모델·ε·표본 경로와 연결된 메타데이터, 공격 성공·실패를 함께 담은 다른 선종의 비교 PNG가 필요합니다. 새 자료는 연구 감사를 거친 뒤 연결합니다.</p></AccordionContent></AccordionItem></Accordion></section>
 <section className="evidence-footer"><div><span className="eyebrow">TRACEABLE BY DESIGN</span><h3>모든 숫자에는 근거가 있습니다.</h3><p>표본 기록에서 계산 · 설명용 3D와 실험 결과 분리</p></div><div><a href={data.repoUrl+"/tree/"+data.sourceCommit} target="_blank" rel="noreferrer">근거 저장소 <ExternalLink size={15}/></a><a href="/evidence/provenance.json" target="_blank">파일 해시·출처</a><span>기준 커밋 {data.sourceCommit.slice(0,7)}</span></div></section></>}
 </div><footer><span><Anchor size={16}/> MARIS · AdversarialAI_Security</span><span>선박 이미지 분류 강건성 연구</span></footer></main>;
}
