export type Counts={n:number;cleanCorrect:number;robustCorrect:number;successes:number;asr:number|null};
export type Sample={id:string;model:string;epsilon:number;path:string;truth:string;cleanPrediction:string;attackPrediction:string;cleanScore:number;success:boolean;asset:string;sourceUrl:string;width:number;height:number;panels:{x:number;y:number;size:number}[]};
export type Evidence={schema:string;sourceCommit:string;repoUrl:string;total:number;models:string[];epsilons:number[];classNames:string[];samples:Sample[];results:(Counts&{model:string;epsilon:number;classes:(Counts&{name:string})[]})[]};
export function validateEvidence(d:unknown):asserts d is Evidence{
 const x=d as Evidence;const fail=()=>{throw Error("Invalid evidence")};
 if(!x||x.schema!=="maris-evidence/v1"||!Number.isInteger(x.total)||x.total<=0||!Array.isArray(x.results)||!Array.isArray(x.samples)||!x.samples.length||!Array.isArray(x.models)||!Array.isArray(x.epsilons)||!Array.isArray(x.classNames))fail();
 function counts(c:Counts){if(![c.n,c.cleanCorrect,c.robustCorrect,c.successes].every(n=>Number.isInteger(n)&&n>=0)||c.n===0||c.cleanCorrect>c.n||c.robustCorrect>c.n||c.successes>c.cleanCorrect||c.asr!==(c.cleanCorrect?c.successes/c.cleanCorrect:null))fail()}
 if(x.results.length!==x.models.length*x.epsilons.length)fail();const keys=new Set();
 for(const r of x.results){counts(r);const key=r.model+":"+r.epsilon;if(keys.has(key)||!x.models.includes(r.model)||!x.epsilons.includes(r.epsilon)||r.n!==x.total)fail();keys.add(key);if(!Array.isArray(r.classes)||r.classes.length!==x.classNames.length||new Set(r.classes.map(c=>c.name)).size!==x.classNames.length)fail();for(const c of r.classes){counts(c);if(!x.classNames.includes(c.name))fail()}for(const field of ["n","cleanCorrect","robustCorrect","successes"] as const)if(r.classes.reduce((s,c)=>s+c[field],0)!==r[field])fail();if(r.epsilon===0&&(r.successes!==0||r.robustCorrect!==r.cleanCorrect))fail()}
 if(new Set(x.samples.map(s=>s.id)).size!==x.samples.length)fail();for(const s of x.samples){if(!keys.has(s.model+":"+s.epsilon)||s.cleanPrediction!==s.truth||s.success!==(s.attackPrediction!==s.truth)||!Number.isFinite(s.cleanScore)||s.cleanScore<0||s.cleanScore>1||!s.asset.startsWith("/evidence/images/")||s.asset.includes("..")||!s.sourceUrl.startsWith(x.repoUrl+"/blob/"+x.sourceCommit+"/")||s.panels.length!==3)fail();for(const p of s.panels)if(![p.x,p.y,p.size].every(Number.isFinite)||p.x<0||p.y<0||p.size<=0||p.x+p.size>s.width||p.y+p.size>s.height)fail()}
}
